**Step 1: Download the Dataset**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

df=pd.read_csv("/content/Student_Performance.csv")

# Load the dataset using pandas.
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

**Step 3: Data Understanding and Exploration**

In [ ]:
# Display first 5 rows
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [ ]:
# Check dataset shape.
df.shape

(10000, 6)

In [ ]:
# 4. Check null values.
df.isna()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
9995,False,False,False,False,False,False
9996,False,False,False,False,False,False
9997,False,False,False,False,False,False
9998,False,False,False,False,False,False
9999,False,False,False,False,False,False

In [ ]:
df.isna().any().any()

np.False_

In [ ]:
df.isnull()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
9995,False,False,False,False,False,False
9996,False,False,False,False,False,False
9997,False,False,False,False,False,False
9998,False,False,False,False,False,False
9999,False,False,False,False,False,False

In [ ]:
# Check data types.
df.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [ ]:
df['Extracurricular Activities'].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
df['Extracurricular Activities']=df['Extracurricular Activities'].map({'Yes':1,'No':0}).astype(int)

In [ ]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

**Step 4: Data Preprocessing**

In [ ]:
X=df.iloc[ : , :-1]
y=df.iloc[ : , -1]

In [ ]:
X

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5
...,...,...,...,...,...
9995,1,49,1,4,2
9996,7,64,1,8,5
9997,6,83,1,8,5
9998,9,97,1,7,0
9999,7,74,0,8,1

In [ ]:
y

0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ...
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: Performance Index, Length: 10000, dtype: float64

**Step 5: Train-Test Split**

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train.shape,y_train.shape

((8000, 5), (8000,))

In [ ]:
X_test.shape,y_test.shape

((2000, 5), (2000,))

**Step 6: Model Building**

In [ ]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

**data -> y=m1x1+m2x2+m3x3+m4x4+c**

In [ ]:
reg.coef_ #m

array([2.85248393, 1.0169882 , 0.60861668, 0.47694148, 0.19183144])

In [ ]:
reg.intercept_ #c

np.float64(-33.92194621555638)

**Step 7: Model Evaluation**

**Training Performance**

In [ ]:
2.85248393*5+1.0169882*49+0.60861668*0+0.47694148*7+0.19183144*5-33.92194621555638

34.47064279444361

In [ ]:
y_train

9254    36.0
1561    25.0
1670    59.0
6087    22.0
6669    40.0
        ...
5734    48.0
5191    51.0
5390    44.0
860     20.0
7270    24.0
Name: Performance Index, Length: 8000, dtype: float64

In [ ]:
X_train

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
9254,5,49,0,7,5
1561,2,48,1,7,6
1670,2,81,0,7,2
6087,2,46,0,6,1
6669,8,47,0,9,0
...,...,...,...,...,...
5734,8,50,1,6,6
5191,4,68,0,9,3
5390,9,48,0,7,6
860,1,47,0,9,0
7270,2,46,0,6,6

In [ ]:
train_predictions=reg.predict(X_train)

In [ ]:
train_predictions

array([34.47064278, 25.69665091, 57.88131903, ..., 45.05542174,
       21.02145642, 22.57711635])

In [ ]:
from sklearn.metrics import r2_score,root_mean_squared_error

print(f"Train Accuracy : {r2_score(y_train,train_predictions)}")
print(f"Train Loss : {root_mean_squared_error(y_train,train_predictions)}")

Train Accuracy : 0.9886898790682355
Train Loss : 2.0419931071198567

**Test Peformance**

In [ ]:
from sklearn.metrics import r2_score,root_mean_squared_error

print(f"Train Accuracy : {r2_score(y_test,reg.predict(X_test))}")
print(f"Train Loss : {root_mean_squared_error(y_test,reg.predict(X_test))}")

Train Accuracy : 0.9889832909573145
Train Loss : 2.0205515085050054

**Step 8: Sample Prediction Testing**

In [ ]:
hours_studied=8
previous_scores=88
extra_curricular_activities=1
sleep_hours=8
papers=8

import warnings
warnings.filterwarnings("ignore")

result=reg.predict([[hours_studied,previous_scores,extra_curricular_activities,sleep_hours,papers]])
print(f"Student Performance : {result}")

Student Performance : [84.35168682]

**Step 9: Save Model as Pickle File**

In [ ]:
import pickle

with open("MLR.plk","wb") as f:
  pickle.dump(reg,f)

In [ ]:
with open("MLR.plk","rb") as f:
  m=pickle.load(f)

**Step 10: Load Model from Pickle File**

In [ ]:
hours_studied=8
previous_scores=88
extra_curricular_activities=1
sleep_hours=8
papers=8

import warnings
warnings.filterwarnings("ignore")

result=m.predict([[hours_studied,previous_scores,extra_curricular_activities,sleep_hours,papers]])
print(f"Student Performance : {result}")

Student Performance : [84.35168682]